### ISSUE TITLE
[BUG] Aircraft squawk codes are being reassigned

### ISSUE THREAD

**Issue by nrankin18** [collink2451/ATCTrainer-IssueTracking#200]
### What happened?

When starting a scenario with aircraft with predefined squawk codes, they spawn in with their assigned squawk codes in the flight plan, then the vNAS server overwrites the squawk code. This results in a revision being applied to all flight plans/strips.

I would recommend removing the squawk code field from the aircraft scenario.

**Comment by collink2451** [comment]
At this time I am not going to modify this since ATCTrainer will be released before vNAS/CRC and assigning squawks is an important feature. Once vNAS/CRC is available and stable-ish on the sweatbox we can remove it. For now, if you don’t want duplicates I would recommend setting the squawk code in the aircraft file to 0000 or 1200 and it shouldn’t attempt to assign those codes or deal with the duplicates.
